### ISSUE TITLE
publish module

### ISSUE THREAD

**Issue by svenvreenen** [directus-labs/agency-os#107]
Hi Team, is it possible to publish the custom module written as a package to be used in Nuxt to access the directus/sdk?
The current modules are giving some extra headache and don't seem to be seamless with the new sdk.

**Comment by bryantgillespie** [comment]
Don't have any current plans to publish the custom module here as a separate Nuxt module. Personally, would love to have an "official" Nuxt module though.

I thought the one listed on the Nuxt website had a `dev` branch that was basically a pass through for the SDK but not sure if it ever got finished or released.

Have you looked at this one?
The Directus module in this project is based in part (especially the composable usage) on it.
https://github.com/becem-gharbi/nuxt-directus
