### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [directus-labs/agency-os#113]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Agency-OS application as shown [here](https://elest.io/open-source/agencyos). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by revenue share upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by bryantgillespie** [comment]
Thanks for the suggestion here and adding Agency OS as a option on your website. That said, we're not going to add this as a deployment option to the official AgencyOS documentation.

1. We do not have any official partnership with Elestio.
2. There is no mention of the Directus license requirements on the Elestio site. While AgencyOS is under the MIT license, [Directus is licensed under BSL1.1](https://github.com/directus/directus?tab=License-1-ov-file#readme). 

Are you deploying Directus v10+ for Elestio customers?

If you're seeking an official partnership with Directus and want to become compliant with our license, please reach out to our team.
https://directus.io/demo
