### ISSUE TITLE
"[Invoices] Generate Number" flow not working

### ISSUE THREAD

**Issue by Abdallah-Awwad** [directus-labs/agency-os#69]
When creating a new invoice this flow fails as shown. 
![image](https://github.com/directus-community/agency-os/assets/129249191/a6f51010-25cf-4fcc-b911-b20e714285af)

it's trying to find a collection called `os_invoice_config` but it doesn't exist. 
![image](https://github.com/directus-community/agency-os/assets/129249191/35514947-f929-4015-ad36-d5bf1aa20947)

**Comment by baguse** [comment]
![image](https://github.com/directus-labs/agency-os/assets/36828138/fb708407-889e-414d-8482-3086eb7a70c0)
This is a temporary workaround, It's worked well on my end

**Comment by baguse** [comment]
I have created a PR, hope it merged soon

**Comment by Abdallah-Awwad** [comment]
@baguse Yep, it works! 
Thank you 🤝🏻

**Comment by baguse** [comment]
The PR is already merged, you can try to create a new project @Abdallah-Awwad

**Comment by den5o** [comment]
I just deployed agencyos and the invoice workflow doesn't work.

Neither does this workaround.

> ![image](https://github.com/directus-labs/agency-os/assets/36828138/fb708407-889e-414d-8482-3086eb7a70c0) This is a temporary workaround, It's worked well on my end
