### ISSUE TITLE
Hydration style mismatch

### ISSUE THREAD

**Issue by kevincam3** [directus-labs/agency-os#71]
Directus hosted on Railway
Nuxt hosted on my localhost machine port 3001

![image](https://github.com/directus-labs/agency-os/assets/870934/8cafe0b5-0b50-42d6-9489-0da11cf26184)

![image](https://github.com/directus-labs/agency-os/assets/870934/ced3bd4b-08c9-40c7-955c-b96898dc1c0c)

**Comment by bryantgillespie** [comment]
Try upgrading to the latest version of Nuxt and Vue.

**Comment by kevincam3** [comment]
Tried that, it just created more issues.
![image](https://github.com/directus-labs/agency-os/assets/870934/766bf378-8d62-4f9a-96dd-8c6687d9614f)

**Comment by kevincam3** [comment]
I turned off SSR and it's working fine now.
