### ISSUE TITLE
Self hosted directus server with agency os results in 500 error on init

### ISSUE THREAD

**Issue by bilguunbill** [directus-labs/agency-os#73]
I have gone through all the setups starting with self hosting directus and configuring the agency os template on directus (visible on my directus dash) and used vercel to deploy the agency os template. After Agency Os is deployed i get 

{ "url": "/", "statusCode": 500, "statusMessage": "", "message": "Cannot read properties of null (reading 'id')", "stack": "" } error 

on my window. I originally thought it was an error with the backend connection but when i checked the directus logs the frontend seems to have connected successfully with the backend. I am not a pro developer so maybe this is a newbie issue, is there anyone who has had the same error with a solution.
The last request from the frontend to the backend is the following: 
directus-1  | [20:42:52] GET /items/forms?filter=%7B%22key%22%3A%7B%22_eq%22%3A%22newsletter%22%7D%7D 200 21ms

my vercel deployment is at https://news-agency-two.vercel.app/

**Comment by bryantgillespie** [comment]
It looks to be an issue with CORS

![ScreenShot 2024-03-18 at 23 33 42@2x](https://github.com/directus-labs/agency-os/assets/23302570/8ea8b58e-cd5d-4a40-bc16-f79001106bf5)

You'll want to add your frontend domain to your CORS settings for your Directus project.
https://docs.directus.io/self-hosted/config-options.html#cors

**Comment by bilguunbill** [comment]
You are right, however in my docker compose yml env for directus cors enabled is false. would there be a cors config i need to do for the frontend agency os code?

**Comment by bryantgillespie** [comment]
That's the problem then right. Because you're not allowing Cross Origin Resource Sharing.

![ScreenShot 2024-03-19 at 11 36 22@2x](https://github.com/directus-labs/agency-os/assets/23302570/e4669424-ef91-4f8b-847c-2eb8d09cd472)

Try setting
CORS_ENABLED = true
and
CORS_ORIGIN = yourdomain1.com,yourdomain2.com

**Comment by bilguunbill** [comment]
Well, i feel so foolish. I had not realized that I had the CORS_ENABLED to false. Thank you very much for the valuable insight.

**Comment by bilguunbill** [comment]
Close
