### ISSUE TITLE
updates are not automatic

### ISSUE THREAD

**Issue by JOduMonT** [directus-labs/agency-os#74]
not sure it is related but
in my directus the build hook URL point to nelify while I followed the first video and it deployed the frontend on Vercel.
if I run a manual deployment in vercel the change are effective
how could I make sure any change made in the directus are automaticaly reflected in nuxt?

**Comment by bryantgillespie** [comment]
You'd just update the build hook URL inside your Directus instance to your Vercel one.
https://vercel.com/docs/deployments/deploy-hooks

**Comment by bryantgillespie** [comment]
Here's a guide from the Directus docs.
https://docs.directus.io/guides/headless-cms/trigger-static-builds/vercel.html#triggering-static-site-builds-with-vercel
