### ISSUE TITLE
NAV Bar not working fine

### ISSUE THREAD

**Issue by tecnicosya** [directus-labs/agency-os#78]
Hi guys, I dont know how to solve this problem.
If I try to click on any item on the nav bar not load the content, the URL address change ok, but the content is not filled.
But if I try enter on the URL or referesh, the content load ok.

I upload a video to show it.
[AgencyOS_error_load.webm](https://github.com/directus-labs/directus-template-cli/assets/12757668/6bfd9a75-f358-4090-a687-b3900bd964d5)

**Comment by bryantgillespie** [comment]
I'm guessing it's either an authentication issue or maybe a CORS issue.

Nuxt offers "universal rendering" which means it renders the first page on the server and then subsequent pages on the client.

**Comment by bryantgillespie** [comment]
I'd start by checking your URLs and any static tokens you're using.

**Comment by juliusm254** [comment]
Facing same issue.

@bryantgillespie what do you mean check URLs?

**Comment by juliusm254** [comment]
set CORS = true.

It works
