### ISSUE TITLE
docker compose on MacOS: "chown: changing ownership of '/var/lib/postgresql/data': Permission denied"

### ISSUE THREAD

**Issue by Jehu** [directus-labs/agency-os#90]
postgress does not start because of this error:
`chown: changing ownership of '/var/lib/postgresql/data': Permission denied`

![CleanShot 2024-04-30 at 09 31 12@2x](https://github.com/directus-labs/agency-os/assets/650836/58f14447-51ad-40a5-96a9-7a4e51d1dcb1)

**Comment by ComfortablyCoding** [comment]
This is most likely a permission/mapping issue on wherever you are hosting or attempting to start docker. I am going to go ahead and close this as it is more of a directus problem than anything specific to agency-os.

See the following issue for possible solutions/suggestions.
- https://github.com/directus/directus/issues/20088
