### ISSUE TITLE
Unable to Load Images in Portal Due to 403 Error Despite Administrator Access

### ISSUE THREAD

**Issue by Abdallah-Awwad** [directus-labs/agency-os#98]
I've noticed that when I log into the portal (even as an administrator) and try to view any organization's folder, I can see the available cards for existing images, but they never load. 
![image](https://github.com/user-attachments/assets/10baa2fa-0a02-47e5-8be0-11292ec59545)

When I checked the network tab for the images, the response is 403. However, when I try to access the image with Postman, for instance, and attach the token, it can be viewed normally.

## To reproduce :
1. Make a fresh copy.
2. Add any image to the `Directus` folder, for example.
3. Attempt to view it in the portal (files tab).

**Comment by ComfortablyCoding** [comment]
Thanks for the report! Is this using the latest `agency-os` version and was this working previously?

**Comment by Abdallah-Awwad** [comment]
Thank you for considering! 
Yes, I'm using the latest version. 
> P.S. Looking into this it seems no auth/cookie is being set on asset requests making it a public request

Do we have a function in nuxt/directus SDK that allows us to attach authentication to asset requests?

**Comment by ComfortablyCoding** [comment]
>Do we have a function in nuxt/directus SDK that allows us to attach authentication to asset requests?

As of now a way to resolve this issue is to do the following:

After this line
https://github.com/directus-labs/agency-os/blob/019fd3c7e0aa227c13df9ac5f46f4d734cc52e6b/modules/directus/runtime/plugins/directus.ts#L30

We add this code
```js
useCookie('directus_session_token').value = value.access_token
```

In doing so we ensure all requests now have the correct cookie header. This solution is not necessarily optimal, I will need to see if their is a better way to do this.

**Comment by Abdallah-Awwad** [comment]
Hey @ComfortablyCoding, thanks for the info and sorry for the late reply.

I did try your suggestion, and I can confirm that a cookie named `directus_session_token` does exist on the client-side. However, the issue with the missing cookie in the request header persists.

I'm ready to dig deeper into this. Got any ideas on what to check next? I have more time to dedicate to troubleshooting now.

**Comment by ComfortablyCoding** [comment]
> Hey @ComfortablyCoding, thanks for the info and sorry for the late reply.
> 
> I did try your suggestion, and I can confirm that a cookie named `directus_session_token` does exist on the client-side. However, the issue with the missing cookie in the request header persists.
> 
> I'm ready to dig deeper into this. Got any ideas on what to check next? I have more time to dedicate to troubleshooting now.

From my testing adding that cookie should be all that is needed. It works fine for me once the above code is added.

Once #100 is merged I plan to update the directus client to start using `session` mode which should resolve this issue.

**Comment by ComfortablyCoding** [comment]
I have opened #103 as the potential fix for this, please let me know if this resolves the issue for you

**Comment by Abdallah-Awwad** [comment]
Thank you! 
I will try it as soon as I can 

> You might need to update some of the cookie rules for it to work.
Sorry, but what do you mean?

**Comment by ComfortablyCoding** [comment]
> > You might need to update some of the cookie rules for it to work.
> 
> Sorry, but what do you mean?

If your frontend and backend are not on the same domain (e.g. cross site) you will most likely need to set `SameSite=None` and `Secure=true` on the backend for it to work.

**Comment by Abdallah-Awwad** [comment]
After reproducing the issue, I encountered CORS problems when I'm trying to log in (both locally and on HTTPS).
Once I adjusted `CORS_ORIGIN: 'true'`, it worked like a charm! 🔥

I think we need to update the [docker-compose.yaml](https://github.com/directus-labs/agency-os/blob/main/.directus/docker-compose.yaml) accordingly if that's the case.

**Comment by ComfortablyCoding** [comment]
As that seems to be a setup specific setting I will leave it as is for now. If enough reports come in of the issue we can re-visit it.
